### ISSUE TITLE
Keep alive compability

### ISSUE THREAD

**Issue by VRuzhentsov** [redxtech/vue-plyr#10]
In theory, it should initially work. But in the case of returning to the tab back, the component is renders again, and makes GET requests too

http://joxi.ru/5md14y0SvwkW42

**Comment by redxtech** [comment]
This is most likely a problem with vue it self, or at least intended behavior of some sort. I'm not sure how I would achieve this function, so I will be closing the issue, but if you would like to send a PR addressing this I would happily consider it.
