### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by ericlaaper** [redxtech/vue-plyr#100]
Since today I got this message

A cookie associated with a cross-site resource at https://vimeo.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Hope you can find something to this.

Have a great day

Eric

**Comment by redxtech** [comment]
That is something to do with the vimeo player, not vue-plyr or plyr.
I'll close this now.
