### ISSUE TITLE
How can I open a video on an iPhone immediately in native ios fullscreen mode using plyr methods?

### ISSUE THREAD

**Issue by vk22** [redxtech/vue-plyr#110]
I tryed plyr methods:
player.play()
player.fullscreen.enter();

and turned iosNative to true

but it fires once of 10 ((

**Comment by redxtech** [comment]
Maybe run it on `mounted()`, and if that doesn't work, try a `nextTick()`.

In any case, this is more an issue with (upstream)[/sampotts/plyr].
