### ISSUE TITLE
Microsoft Edge Expected identifier, string or number 

### ISSUE THREAD

**Issue by Robinrrr** [redxtech/vue-plyr#116]
First of all many thanks for the dependency!
Unfortunately I have a bug in the Edge Browser and I don't know how to fix it.

I have used your package in the SSR version

**Browser:**
Microsoft Edge

**Error Message:**
`Expected identifier, string or number `

**Comment by FlorianFranconi** [comment]
Hi, same error on IE11.

I use the version: **6.0.4**

**Browser:**
Internet Explorer 11

**Error Message:**
`SCRIPT1003: ':' attentedu`

From my research, I think the problem is here:
```
props: {
options: {
      type: Object,
      required: false,
      default () {
        return {}
      }
    },
```

**Comment by FlorianFranconi** [comment]
Hi, 

I checked also on IE11 and I think I know where the probleme

In the props there is an invalid json (for Edge and IE11)

Here the actual props 

```js
props: {
    /** Options object for plyr config. **/
    options: {
      type: Object,
      required: false,
      default () {
        return {}
      }
    },
    /** Array of events to emit from the plyr object **/
    emit: {
      type: Array,
      required: false,
      default () { return [] }
    }
  },
```

The default function seems to be the problem.

I suggest this instead

```js
props: {
    /** Options object for plyr config. **/
    options: {
      type: Object,
      required: false,
      default: {}
    },
    /** Array of events to emit from the plyr object **/
    emit: {
      type: Array,
      required: false,
      default: []
    }
  },
```

Thanks

**Comment by Sorion** [comment]
Hi, 

I checked also on IE11 and I thinkthe issue is in the props.

In the props there is an invalid json (for Edge and IE11)

Here the actual props 

```js
props: {
    /** Options object for plyr config. **/
    options: {
      type: Object,
      required: false,
      default () {
        return {}
      }
    },
    /** Array of events to emit from the plyr object **/
    emit: {
      type: Array,
      required: false,
      default () { return [] }
    }
  },
```

The default function seems to be the problem.

I suggest this instead

```js
props: {
    /** Options object for plyr config. **/
    options: {
      type: Object,
      required: false,
      default: {}
    },
    /** Array of events to emit from the plyr object **/
    emit: {
      type: Array,
      required: false,
      default: []
    }
  },
```

**Comment by redxtech** [comment]
Default cannot be an object, because that would cause every player intance to have to the same object as the prop value, because of the way that objects work. I would recommend polyfilling your project, that might help with the issues on IE11.

**Comment by nmedias** [comment]
nuxt.config.js add  transpile: ['vue-plyr']
