### ISSUE TITLE
npm version 2.1.1

### ISSUE THREAD

**Issue by jwjcmw** [redxtech/vue-plyr#13]
It looks like the version 2.1.1 that is on npm isn't correct...it doesn't have the emit code.  I was trying to use that as I have some custom stuff that still requires plyr 2.  Any chance of updating it?

**Comment by redxtech** [comment]
I honestly have no idea how I would push an update to an older version of the app, as this is my only package on NPM. If you know how to do that I can give it a shot if you tell me. Also, what is the custom stuff that requires v2? If it has to do with the errors with v3 so far I should be able to fix those soon.

**Comment by jwjcmw** [comment]
You have one more package on NPM than I do, so I'm not going to be much help there. :)  The custom stuff is plyr specific (custom controls) that I haven't had time to make compatible with v3.  I can work around this, and it might just encourage me to get plyr upgraded.
