### ISSUE TITLE
controls stretched out of video frame

### ISSUE THREAD

**Issue by thekswenson** [redxtech/vue-plyr#15]
I have a cordova F7 project that I'm trying to using your nice components with.
I added
```
import VuePlyr from 'vue-plyr';
import 'vue-plyr/dist/vue-plyr.css';
Vue.use(VuePlyr)
```
to the main.js file and have a simple template in which I'm trying to use Plyr:
```
<template>
  <f7-page>
    <f7-navbar title="This month's video" back-link="Back"></f7-navbar>

    <div class="block">    
    <plyr>             
      <video>
        <source src="static/videos/video.mp4" type="video/mp4"> 
      </video>                                                  
    </plyr>                                         
    </div>    
  </f7-page>
</template> 
            
<script>
  import { f7Navbar, f7Page, f7BlockTitle } from 'framework7-vue';
                                                                  
  export default {                                                
    components: {                                                 
      f7Navbar,                                                   
      f7Page,     
      f7BlockTitle,
    },             
  };                     
</script>
```
I end up with a plyr player that has the controls stretched off the side of the video frame like so:
![screenshot from 2018-04-29 16-23-04](https://user-images.githubusercontent.com/9959942/39407733-14bd529e-4bcb-11e8-91b8-57029220674d.png)
Is this an issue with vue-plyr, plyr itself, or am I using these wrong?

**Comment by jwjcmw** [comment]
It looks like there is a conflict between the plyr css and F7...can you inspect that play button and see what is styling it?  I'm going to guess there is a "width: 100% !important" somewhere in the F7 css on a button that is overriding plyr's style.

**Comment by thekswenson** [comment]
Yikes!
Yes I find the following in the framework7.css file:
```
button {
  width: 100%;
}
```

Would you have any advice for me, or point me in the direction of some reading where for this.  I don't yet have a good handle on how to limit the scope of css, as I'm rather new to all of this.
 
Thanks a ton for the help!

**Comment by jwjcmw** [comment]
I would probably reset the buttons within the context of the .plyr class, which wraps the buttons that are causing the problem...so you would need something like:
.plyr button {
    width: inherit;
}
which would be added to your own css that is imported into the project.

**Comment by thekswenson** [comment]
Thank you @jwjcmw !

**Comment by jwjcmw** [comment]
Just FYI, I brought it up in the plyr repo, and there should be a fix that takes care of it soon...
https://github.com/sampotts/plyr/issues/928
