### ISSUE TITLE
Error: Setting the playback rate is not enabled for this video.

### ISSUE THREAD

**Issue by marctaule** [redxtech/vue-plyr#165]
I get this error in my console. Do you know why? I use vimeo and youtube videos.
Thanks!

`Error: Setting the playback rate is not enabled for this video.`

![Captura de pantalla 2020-04-03 a les 17 58 00](https://user-images.githubusercontent.com/46464634/78380773-b34e6f80-75d4-11ea-9bf3-61f7cd3ac6d1.png)

**Comment by redxtech** [comment]
I am not sure. I would recommend reading the upstream documentation for this.

**Comment by core01** [comment]
Hi @redxtech could you, please, update plyr dependency to at least 3.6.1 version?  Because they had fix that error https://github.com/sampotts/plyr/releases/tag/v3.6.1

**Comment by redxtech** [comment]
Closing because I'm updating the plyr version now
