### ISSUE TITLE
Poster is not showing

### ISSUE THREAD

**Issue by stanislavhannes** [redxtech/vue-plyr#166]
Hey,
I am using your plugin with Nuxt 2.12.2 in SSR mode.
So far everything is working like charm, except that the poster won't appear.
I tried to use a relative and an absolute url from a different website. Nothing seems to work.

If l execute the following
``` 
mounted() {
    this.player.on('ready', () => {
      console.log(this.player.poster);
    });
  }
```
the resullt is null

When I try to set the poster path with `this.player.poster = this.posterSrc;` and then force to rerender the `<vue-plyr :key="test"> .... </vue-plyr>` component, still no change.

Also I get in the console `(index):1 GET http://localhost:3000/impressionen/null 404 (Not Found)` (/impressionen is the site where I load the video)

Any Idea what it could be?

**Comment by redxtech** [comment]
It looks like the site is trying to load the poster as a relative URL. Did you include the protocol (`https://`) in the source URL?

**Comment by stanislavhannes** [comment]
Yep, I tried this, but without success. 
Strange thing is, if I put it in "picture in picture" mode, I can see a blury and less colorfull version of the poster inside the player as placeholder during the mode.

**Comment by redxtech** [comment]
What's the console error when you try this?

**Comment by stanislavhannes** [comment]
Still the same like above `(index):1 GET http://localhost:3000/impressionen/null 404 (Not Found) ` . If I leave poster empty I also get this

**Comment by redxtech** [comment]
That's quite odd. I'd recommend taking it up with upstream. Have you looked at what the attribute reads in the html?

**Comment by stanislavhannes** [comment]
What do you mean with upstream? U mean debugging? ... Yes, in HTML the path looks correct `poster="http://localhost:3000/impressionen/FeierabendFusionZ-AftermoviePoster.jpg"`

**Comment by stanislavhannes** [comment]
Sometimes the poster shows up for just a second and then disappears again

**Comment by redxtech** [comment]
No by upstream I mean [this](https://github.com/sampotts/plyr).

**Comment by stanislavhannes** [comment]
Ok, I found the reason why the poster is hiding after a second. I have the following code:
```
<VuePlyr :key="test" ref="plyr">
      <video id="player" :src="defaultSrc" :poster="posterSrc">
        <source
          v-for="(item, index) in videoSource"
          :key="index"
          :src="item.src"
          :type="item.type"
          :size="item.size"
        />
      </video>
    </VuePlyr>
```

And this is my videoSource array:
```
videoSource: [
            {
              src: `${resourceDir}${feierFusionZ}480p.webm`,
              size: '480',
              type: 'video/webm'
            },
            {
              src: `${resourceDir}${feierFusionZ}480p.mp4`,
              size: '480',
              type: 'video/mp4'
            },
            {
              src: `${resourceDir}${feierFusionZ}720p.webm`,
              size: '720',
              type: 'video/webm'
            },
            {
              src: `${resourceDir}${feierFusionZ}720p.mp4`,
              size: '720',
              type: 'video/mp4'
            },
            {
              src: `${resourceDir}${feierFusionZ}1080p.webm`,
              size: '1080',
              type: 'video/webm'
            },
            {
              src: `${resourceDir}${feierFusionZ}1080p.mp4`,
              size: '1080',
              type: 'video/mp4'
            }
          ]
``` 
So my defaulSrc in `<video>` is actually the src from the mp4 and 720p item insider videoSource my videoSource array. If I leave the don't use src inside `<video>`, the poster will be displayed. But unfortunately I can't start the video directly. Only if I choose a value inside the quality setting (e.g. 720p). Is there a way to use the player without the default source?

**Comment by stanislavhannes** [comment]
I found the reason for the 404 error in the console.  It was the Nuxt Lazy Load package. But still no poster.

**Comment by stanislavhannes** [comment]
Finally! I found a workaround.
In [this](https://github.com/sampotts/plyr/issues/1763) ticket they had issues with the poster too. It was related to the new plyr version 3.5.10. So I made a fork from your repo and downgraded the plyr version from 3.5.10 to 3.5.6 (3.5.8 didn't work) and now it works!
Hope there will come a better solution in the near future.

**Comment by redxtech** [comment]
Glad you found a workaround! I'll close this for now, but if you still have this issue once I update to the latest version of plyr, feel free to open it again (or a new one). However, it's more likely an upstream issue, so opening an issue there first might be better.
