### ISSUE TITLE
CORS error is not trigerred on error event

### ISSUE THREAD

**Issue by fayazara** [redxtech/vue-plyr#167]
I am trying to stream some hls content using this method https://github.com/redxtech/vue-plyr/issues/29. It works but for some links I get a CORS error, I am not able to catch this error from the error event. 

```
computed: {
    player() {
      return this.$refs.plyr.player;
    }
  },
  mounted() {
    if (Hls.isSupported()) {
        const hls = new Hls();
        hls.loadSource(this.channel.url);
        hls.attachMedia(this.player.media);
        window.hls = hls;
    }
    this.player.on("error", err => console.log("errr ocurred", err));
  }
```

The console prints nothing, anything I can do to catch this?

**Comment by fayazara** [comment]
I have added a hack for now I make a http request in mounted method to see if it returns a 200 response, it not I handle the error, wish there was built in support for it though

**Comment by redxtech** [comment]
I'm going to close this, but I'm pretty sure it's something you should take up with upstream instead of this repo here.
