### ISSUE TITLE
get duration on ready and before video play

### ISSUE THREAD

**Issue by arggasasao** [redxtech/vue-plyr#169]
Hi I want to get duration of video before user hit play button.
The video is loaded and I can play it.
What I doing wrong?

```html
<vue-plyr ref="plyr" class="player__plyr">
	<video :src="getInitVideo"></video>
</vue-plyr>
```

```javascript
mounted() {
  this.player.on("ready", () => {
    console.log("Video ready: duration:", this.player.duration)
    this.videoTimeTotal.duration = this.player.duration
  })
}
```

### Expected behaviour

<pre>
  console output: Video ready: duration: 911.223566
</pre>

### Actual behaviour

<pre>
  console output: Video ready: duration: 0
</pre>

### Environment
package.json
- "vue": "^2.6.11",
- "plyr": "^3.5.10",
- "vue-plyr": "^6.0.4",
- Browser: chrome 
- Operating System: Macos Catalina

**Comment by DiAvisoo** [comment]
this.player.on('ready', () => {
      this.player.embed.getDuration().then(function(duration){ 
        console.log(duration)
      });
    });

**Comment by redxtech** [comment]
Looks like you've found a solution, so I'll close this issue.
