### ISSUE TITLE
Syntax error Nuxt v2.11.0 on generate

### ISSUE THREAD

**Issue by KristianJohansenVakwerk** [redxtech/vue-plyr#173]
Hi!

Using vue-plyr v^6.0.4 and everything works perfect when I run npm run dev but when I run npm run generate do I get this error. 

Anyone having the same issue of know how to fix it? 

ERROR in ./node_modules/plyr/dist/plyr.css (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/plyr/dist/plyr.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
JisonParserError: Parse error on line 1: 
...r(--plyr-control-padding,calc(var(--plyr-control-spacing,10px) * .7))) - (var(-...

**Comment by ItsNash0** [comment]
running into the same issue... it won't work on Nuxtjs because of this

**Comment by antzah** [comment]
Getting the same error on a "plain" Vue project 😣

**Comment by antzah** [comment]
Seems to be a problem with the plyr package – after I downgraded it to 3.5.10, everything works.

**Comment by ItsNash0** [comment]
Do you manage to show the fullscreen button on production with nuxt?

**Comment by redxtech** [comment]
Looks like this was an issue with plyr, which has fixed it, and the updated version has been included here.
