### ISSUE TITLE
Quality switcher for HLS

### ISSUE THREAD

**Issue by akbarjoudi** [redxtech/vue-plyr#185]
It appears that HLS quality switching is a highly requested feature and several other players seem to have this plugin. I see the ground work was laid with this commit/issue below.
Is there any time frame to implement this feature? I think overall it's a great player and loads HLS videos faster for me than other open source players.

**Comment by kpguru20001** [comment]
I m also having an issue with quality controller

**Comment by redxtech** [comment]
This is something to take up with [upstream](/sampotts/plyr). I can't do anything about this.
