### ISSUE TITLE
Hi, Thanks for vue-plyr, it works almost pefectly for me but as I use the video as background I would like to disable the controls. How can I do it?

### ISSUE THREAD

**Issue by laugoabad** [redxtech/vue-plyr#186]

**Comment by jwjcmw** [comment]
You would do that in the config values that you pass to plyr...see this: https://github.com/sampotts/plyr/issues/414  But as is noted in that issue, plyr is overkill for a background...you could probably just use a video tag.

**Comment by redxtech** [comment]
@jwjcmw is correct.
