### ISSUE TITLE
CSS Custom Properties not working with vue-plyr and Nuxt SSR

### ISSUE THREAD

**Issue by simonhrogers** [redxtech/vue-plyr#197]
Hi there, 

Got a confusing issue!

Setup as per the docs, with Nuxt @2.8.1, the CSS custom properties are flattened to their static values when I run my app – meaning my updates to the variables get ignored. 

If I render components containing vue-plyr on the client only, the CSS builds correctly – do you have any experience with this?

Ideally I would be able to render them on the server too

Thanks,

Simon

**Comment by redxtech** [comment]
I have not encountered this specific issue, but when using SSR I will make sure that vue-plyr is client rendered only. Since it's nuxt that's building the CSS, I'd recommend looking through their docs/issues/etc. to see if it's an issue on their side.
