### ISSUE TITLE
Show ads

### ISSUE THREAD

**Issue by badu22** [redxtech/vue-plyr#199]
Can i show ads if i am not using vi.ai publisher ID? 

when i put 
```
ads: {
enabled: true,
tagUrl: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=' 
}
```

Nothing happens.

**Comment by badu22** [comment]
in console

```
Uncaught DOMException: Blocked a frame with origin "http://127.0.0.1:8080" from accessing a cross-origin frame.
    at hasOwnProperty (<anonymous>)
    at hasOwn (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:153:25)
    at observe (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:980:7)
    at pu.reactiveSetter [as g] (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1055:29)
    at https://imasdk.googleapis.com/js/sdkloader/ima3.js:415:92
    at Map.forEach (<anonymous>)
    at aw.$ (https://imasdk.googleapis.com/js/sdkloader/ima3.js:415:69)
    at yh (https://imasdk.googleapis.com/js/sdkloader/ima3.js:99:335)
    at HTMLIFrameElement.vh (https://imasdk.googleapis.com/js/sdkloader/ima3.js:100:284)
    at HTMLIFrameElement.b (https://imasdk.googleapis.com/js/sdkloader/ima3.js:97:285)
```

**Comment by badu22** [comment]
vue.config.js
```
module.exports = {
    crossorigin: 'anonymous',
    devServer: {
        headers: {
            'Access-Control-Allow-Origin': '*'
        },
        public: '127.0.0.1:8080',
        disableHostCheck: true
    },
};
```

**Comment by badu22** [comment]
repo: https://github.com/badu22/videoPlayer-vue

**Comment by redxtech** [comment]
Hey, this seems like an issue to take up with [upstream](/sampotts/plyr). I don't handle the ads, just the vue wrapper.

**Comment by badu22** [comment]
Error with imasdk happens only in vue enviroment, using vue wrapper.

**Comment by redxtech** [comment]
Odd. You've tested with native plyr on the same address (127.0.0.1:8080) as well?

**Comment by badu22** [comment]
Yes i have (https://github.com/badu22/videoPlayer) it works as expected.

**Comment by liquidvisual** [comment]
@badu22 Did you manage to find a fix for this? I can't gets ads working in Vue either.

**Comment by liquidvisual** [comment]
@badu22 When I run your code I don't see any ads. Is this working on your end?

When I attempt to run ads in Vue (in general) I get a `Blocked a frame with origin "localhost" from accessing a cross-origin frame` error :(

Has anyone managed to get this working?

**Comment by redxtech** [comment]
That looks like an error with whoever if providing the ads. I'm guessing that when working with the ad dashboard you had to specify URLs that would be displaying the ads. If you want to test them on a dev build of the website (ie: running on `localhost`), you will have to specify that in the dashboard, or however that would work.

Another reason could be the ad company blocks showing ads on `localhost` to prevent bots from spinning up the ads and viewing them locally. I'm guessing it only allows it to be loaded on URLs that are not `localhost`.

**Comment by badu22** [comment]
@redxtech i used https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags for testing adds.

**Comment by Kuuzou-cl** [comment]
@badu22  Did you fix it? I'm trying to add VAST too but I got always an error
`Uncaught DOMException: Permission denied to access property "__ob__" on cross-origin object vue.runtime.esm.js:152`
already tried with Vue and Nuxt

**Comment by redxtech** [comment]
I have no idea what the issue could be, but it looks like it's outside the scope of this component. Try using plyr in a vue app without vue-plyr, but other than that I've got nothing.

**Comment by iFeras93** [comment]
this issue is still apper
