### ISSUE TITLE
Offer Sass file over CSS

### ISSUE THREAD

**Issue by rebz** [redxtech/vue-plyr#2]
Would be great if the Sass file was included as an option.

**Comment by redxtech** [comment]
I don't use a sass file here. I just import the dist/plyr.css from plyr. You can get the same file from putting the following code in your sass file after `npm install plyr` or `yarn add plyr`.
```scss
@import '~plyr/src/scss/plyr
```

**Comment by rebz** [comment]
That actually makes more sense. Thank you.

**Comment by mortensassi** [comment]
Like other Plugin Devs it would be preferable to just let the user import the sass in order to modify the appearance. now if you additionally import the scss file you get twice the css in your app and the overrides won't even work since they get overridden by your imported css file

**Comment by maximelebreton** [comment]
Hello.
Please Repoen this issue, and add the ability to disable css style import, or like @mortensassi said, let the dev import the css.
Currently we have no way import our own Sass style, because the default style overrides our custom Sass stylesheet.

Thanks,
