### ISSUE TITLE
Plyr Polyfilled

### ISSUE THREAD

**Issue by radames** [redxtech/vue-plyr#20]
To make vue-plyr compatible with IE you may have to load some polyfills
the original plyr has an option https://github.com/sampotts/plyr/blob/master/src/js/plyr.polyfilled.js 
not sure how to enable this to your vue-plyr component, but would be great to have this option or on info on readmeme

**Comment by redxtech** [comment]
To do this, you would include the polyfills in your own build project.

**Comment by joelfloressottile** [comment]
Any news on this? Would be really helpful
