### ISSUE TITLE
iPhone Auto-Lock Or Using Other Apps Stops Sound

### ISSUE THREAD

**Issue by vahost** [redxtech/vue-plyr#213]
I love this component, but I've run into an issue that I don't know how to fix.

I use vue-plyr to play .m4a files to app users. I used Quasar with Cordova to build my iPhone version of the app.

iPhone users who play the .m4a files are experiencing an issue when the iPhone's auto-lock feature kicks in.

When the iPhone auto-lock setting time gets reached, the audio file keeps playing for a moment, then goes silent. Interestingly enough, the vue-plyr controls indicate that the file is still playing, but no sound comes out of the device.

How can I fix this?

Edit: more info

I found this issue in the plyr forum: https://github.com/sampotts/plyr/issues/1894

As I stated there, I use plyr in vue-plyr, which in turn I use in Quasar/Vue with Cordova to build the iOS app.

Cordova offers a permissions setting for this: playAudioWhenScreenIsLocked in https://github.com/apache/cordova-plugin-media. The permission gets passed when playing an audio or video file using their media object.

The Cordova doc says their playAudioWhenScreenIsLocked parameter defaults to true in Cordova's media plugin, but apparently the same is not the case with plyr and vue-plyr. That probably means I'd have to build my own media player, and I'm not skilled enough to do that.

That's why I was hoping there'd be a way for plyr or vue-plyr to pass a similar permission setting.

**UPDATE: August 27, 2020**

I discovered today that the issue also exists if I try using other apps on the iPhone or iPad. The sound keeps playing in the background for about 20 seconds, then stops. Returning to my app, I see the pause button on the player, but no sound comes out. I have to pause and the start again to get it going.

I do have UIBackgroundModes set to "audio" in my [app]-info.plist file. For good measure, I also added "fetch" and "remote-notification" to the same setting in my plist to see if they would help, but they don't help.

**Comment by MirzaeiDev** [comment]
same

**Comment by redxtech** [comment]
This is something to take up with upstream, as it looks like you've already done. I'm not going to build something like this for a wrapper, so I'll be closing this. Hopefully upstream adds this feature in the future!
