### ISSUE TITLE
Vimeo div element not working

### ISSUE THREAD

**Issue by frutality** [redxtech/vue-plyr#22]
Here is fiddle: https://jsfiddle.net/dcyh5jo8/

"vimeo iframe with progressive enhancement" method works, "vimeo div element" not.

**Comment by frutality** [comment]
It worked like this: `<div id="player" data-plyr-provider="vimeo" data-plyr-embed-id="76979871"></div>`. I got this attribute names from https://github.com/sampotts/plyr readme.

**Comment by redxtech** [comment]
This is most likely a problem with exports in the currently published version. It should be fixed when I publish the new version soon.
