### ISSUE TITLE
player.js:10 POST https://fresnel.vimeocdn.com 500 error

### ISSUE THREAD

**Issue by mvaneijgen** [redxtech/vue-plyr#225]
I'm getting a lot of 500 errors in my console due to the fact that I'm loading a view videos via `vue-plyr` and I don't know where they are coming from (Probably from the Vimeo `player.js` API, but I was wondering if there was a way to suppress via `vue-plyr` those warnings, cause everything is working fine, but it is really hard to debug my code with the console littered with all those errors
```
player.js:10 POST https://fresnel.vimeocdn.com/add/player-stats?beacon=1&session-id=1d50fd0f5887fdfc465175d1ebb0cc3ca0dac8b51599634724 500
```

**Comment by mvaneijgen** [comment]
It was my ad blocker

**Comment by redxtech** [comment]
I've gotten into a panic when the instagram feed for a site I was working on was broken (on production), I had no clue was the issue was. It was also the adblocker. Glad you figured it out!
