### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by AlbertRAR** [redxtech/vue-plyr#23]
Hello,
Is there a changelog? You recently updated from 3 to 4 version. There seem to be some notable changes...

**Comment by AlbertRAR** [comment]
Sure, it is not a problem. I was just curious about changelog)

**Comment by redxtech** [comment]
Just added it now. [Here's a link](https://github.com/redxtech/vue-plyr/blob/master/changelog.md).

**Comment by AlbertRAR** [comment]
Thank you!
