### ISSUE TITLE
Plyr latest is v3.6.2 

### ISSUE THREAD

**Issue by skjnldsv** [redxtech/vue-plyr#233]
This package is still using 3.5.10.

@redxtech is this unmaintained? Do you need help maintaining this library?
There is 10k weekly downloads, this is quite a popular package :)

Thanks! Take care! :v:

**Comment by riderx** [comment]
yes please !

**Comment by redxtech** [comment]
Thanks for letting me know! I've been busy with school, so I haven't had too much time to dedicate to this project recently. I will now be updating the version of plyr, and should keep it updated in the future.

I hadn't realized that this package was reaching that many downloads! Now that I'm aware I guess I'll have to pay more attention to things like this!

Thanks for letting me know again, I'l try to keep it more up to date from now on.

**Comment by redxtech** [comment]
Newest beta version (v7.0.0-beta.2) is using latest version of plyr and is compatible with vue 3!
