### ISSUE TITLE
Could I use it on Wordpress ? 

### ISSUE THREAD

**Issue by myheart1401** [redxtech/vue-plyr#234]
I cannot upload this on wordpress. It said failed. Please help me, I like very much this plugin. Please show me the way to install them on wordpress. Thank you

**Comment by MirzaeiDev** [comment]
hi 
Ye, you can not upload it because it is for Vue.js
you should use it for your WordPress
[https://github.com/sampotts/plyr](https://github.com/sampotts/plyr)
hope to enjoy

**Comment by redxtech** [comment]
This is a wrapper for `plyr` to be used in vue. On the `plyr` page, there is a [list of plugins](https://github.com/sampotts/plyr#plugins--components). There is one for wordpress.
