### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by gadnis** [redxtech/vue-plyr#235]
Hi, 

It would be great to have some player images in wiki. 
Cause not bunch of steps need to be done just to check how it looks like.

Do you think of doing this small improvement to your repo?

**Comment by redxtech** [comment]
I will not be adding images, as that is handled by upstream (this is just a wrapper). If you would like to see what it looks like, view the [original repository](https://github.com/sampotts/plyr).

**Comment by redxtech** [comment]
I've added a demo page at https://redxtech.github.io/vue-plyr/ in lieu of images, hope that helps.
