### ISSUE TITLE
Ads for Vue-Plyr ??

### ISSUE THREAD

**Issue by standfv** [redxtech/vue-plyr#24]
Ads for Vue-Plyr ??

**Comment by redxtech** [comment]
What is your question? If you're asking how to block as like in your other issue, see what I said in that one. #25 .

If you're asking how to add ads, pass your publisher ID and `enabled: true` in the ads option of the options prop when creating a vue-plyr instance.

**Comment by redxtech** [comment]
i'm going to close this issue because it's been more than half a month and you haven't done anything and your question is no where near specific enough to answer.
