### ISSUE TITLE
Subtitles not showing on IOS devices

### ISSUE THREAD

**Issue by havalito** [redxtech/vue-plyr#248]
So this is an odd issue, when I have the player run on iOS devices without adding the inline tag the subtitles wont work, they are available to choose from in the native player but nothing shows. 

I have only seen this behavior on IOS devices, any ideas?

**Comment by redxtech** [comment]
I have not come across this, but it seems like it would be something to take up with upstream. Try with just `plyr`. If the issue is gone, feel free to reopen another issue with some details.
