### ISSUE TITLE
this.$slots.default is not a function

### ISSUE THREAD

**Issue by bekee** [redxtech/vue-plyr#256]
On nuxtjs plugin for "vue-plyr": "^7.0.0-rc.1" i get this.$slots.default is not a function.

Any help on this?

**Comment by redxtech** [comment]
Down grade to v6 until stable v7 comes out. I haven't tested with nuxt on this version yet.

**Comment by redxtech** [comment]
I have just finished testing on nuxt with this version and it's fixed and published on npm as v7.0.0-beta.2.
