### ISSUE TITLE
version 7 not working correctly from cdn

### ISSUE THREAD

**Issue by praine** [redxtech/vue-plyr#257]
The new version 7 of vue-plyr no longer initializes correctly when included from CDN:

"Unknown custom element: <vue-plyr> - did you register the component correctly?"

**Comment by redxtech** [comment]
That change is reflected in the README. Also v7 is not yet fully released.

**Comment by praine** [comment]
sorry, i tried reverting to the previous version but I'm still getting the same issue.. could you advise?
It was working fine until today.

**Comment by redxtech** [comment]
Previous versions worked fine, check examples folders in older commits. Also, I published v7 beta today, so that's why.

**Comment by praine** [comment]
ok, i downloaded previous version from cdnjs.
can I ask why the change with the initialization?

**Comment by redxtech** [comment]
The old method didn't work with vue 3.

**Comment by praine** [comment]
OK, thanks.
