### ISSUE TITLE
vue-plyr instance does not persist on page refresh

### ISSUE THREAD

**Issue by alpkabac** [redxtech/vue-plyr#258]
When I navigate between pages through my navbar or browser's back and forward buttons, Player is there, but when I refresh the page, it is gone without any errors. Before it appears again, I need to navigate between pages. My frontend is fine so I wanted to ask if this is a bug. Also, I am using the stable version.

**Comment by redxtech** [comment]
I got a similar issue somehow last night, I found that when I bumped `rollup-plugin-vue` to the latest beta it got rid of the issue. That is included in the latest released version of vue-plyr (v7.0.0-beta.2). It should be more stable now, and if they were the same issue it should be all good.
