### ISSUE TITLE
Duplicate Vue.js code

### ISSUE THREAD

**Issue by sharq1** [redxtech/vue-plyr#26]
That seems like a bug to me, as https://unpkg.com/vue-plyr@latest includes whole lot of Vue code (>8k lines). Same applies to `dist/vue-plyr.js` file when I install via `yarn`.

I'm new to Vue, but from JS standpoint that seems completely unnecessary and wrong, as this is why you would include `Vue.js` before including `vue-plyr`.

Because of that I'm getting `You are running Vue in development mode.` message twice in console

I'm also getting below, though I'm not quite sure it's related:
```
Unknown custom element: <vue-plyr> - did you register the component correctly?
```
I confirmed that the component registration code in vue-plyr.js is executed, but then calling `Vue.options.components` does not list it.

If I'm however wrong and it's my fault, then please excuse me - as I mentioned, I'm new to Vue ;)

**Comment by sharq1** [comment]
Looks like it's 4.0.0 problem only, as 3.0.0 dist file has less than 400 lines total.

**Comment by redxtech** [comment]
I’ll definitely look into bundled vue code and development mode, but also can you tell me how you’re importing vue-plyr?

**Comment by sharq1** [comment]
Hi @redxtech 
Thank you for looking at this.
I think I know what my problem with registering is.
I'm trying to add vue-plyr to an already existing Rails project, where Vue itself is initialized on `$(document).on('ready', ...)` event, while I see that your library is registering `Vue.component` as soon as the code is executed.

**Comment by horoscop** [comment]
@sharq1 is right, could you please fix this @redxtech ?

Thanks!

**Comment by dominik-bln** [comment]
Importing `Vue` in `index.js` should likely not happen and also automatically registering on the global instance is a bit problematic. Usually this is handled with something like `Vue.use(VuePlyr)`. See here for more details: 

https://alligator.io/vuejs/creating-custom-plugins/#adding-capabilities

**Comment by irazasyed** [comment]
Created a PR based on @dominik-bln's suggestion. Hopefully, it'll be merged soon. Ref: #31. Open for suggestions, will make changes accordingly if required.

This issue has been bothering me as well :P

**Comment by redxtech** [comment]
A PR has been proposed to fix this. I'll take a look and see if it works today.

**Comment by redxtech** [comment]
Just requested a few changes from the PR from @irazasyed  and when they are implemented I will merge.
