### ISSUE TITLE
This.$refs.plyr is undefined

### ISSUE THREAD

**Issue by PiotrekPKP** [redxtech/vue-plyr#260]
When trying to get the player instance (I used app.use(VuePlyr)), this.$refs.plyr returns undefined.

MAIN.TS:
`import VuePlyr from 'vue-plyr'`
`import 'vue-plyr/dist/vue-plyr.css'`
...
`app.use(VuePlyr);`

MY COMPONENT:
`console.log(this.$refs.plyr);`

It shows undefined.
Thanks in advance!

**Comment by kgnfth** [comment]
I have the same problem
did you able to fix it ?

**Comment by PiotrekPKP** [comment]
> I have the same problem
> did you able to fix it ?

You have to add ref="plyr" to your vue-plyr component

**Comment by idesignzone** [comment]
For Vue3 you can use 

```
<template>
  <vue-plyr ref="plyr" >...</vue-plyr>
</template>

<script setup>
import { ref, onMounted, nextTick } from 'vue'

const plyr = ref('plyr')
onMounted(async() => {
  await nextTick(() => {
    plyr.value.player.on('ready', () => console.log('player is ready'));
  });
});
</script>
