### ISSUE TITLE
Origin-Error when using youTube Output

### ISSUE THREAD

**Issue by vouza** [redxtech/vue-plyr#27]
I receive this error when using the youtube "div" variant:

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:8080').`

more infos regarding this issue:
https://issuetracker.google.com/issues/35174286

**Comment by vouza** [comment]
This can be solved by using the iFrame variant instead of the div one. Also you need to add...

`origin=https://localhost:8080"`
to the iframe src url. 

Important: "Use https" even if your environment (site) runs on http.

**Comment by werneckbh** [comment]
This is an issue with the original plyr package and the YouTube API. 

Apparently, this is fixed in version [3.3.23](https://github.com/sampotts/plyr/issues/1108)

**Comment by redxtech** [comment]
I'll test this and update to the latest version. I'll close this issue if it works.

**Comment by redxtech** [comment]
updated to the latest version of plyr in the latest dev build and it appears to be working. Will push to master after a few more fixes. Re-open this issue if the problem continues after I publish a new version to NPM.
