### ISSUE TITLE
Responsive Styling - width ignored

### ISSUE THREAD

**Issue by rebz** [redxtech/vue-plyr#3]
For an internal project we tried using this inside a Modal window. Haven't had much time to debug as of yet. When I get more time in the day I'll try to update this issue but I wanted to go ahead and capture it now.

It seems the player ignores responsive styling on iOS devices (all we've checked so far).

iOS 11, Chrome and Safari

On desktop it appears to work fine. I apologize, I know this doesn't give a lot of info for now. I'll update later.

**Comment by redxtech** [comment]
Which component are you using?
I would recommend using the `<plyr>` wrapper around a video element, and you can add your own styles there.

Also, I do not manage any of the styles. This is just a wrapper around [sampotts/plyr](https://github.com/sampotts/plyr), so making an issue there would probably be a better idea.

**Comment by rebz** [comment]
Tried `<plyr-video>` and `<plyr><video><source>` both had the same issue even when incorporating the Plyr styles directly from their package. I had to add a `max-width: 100%;` to the video element itself no matter the component I used. Might be worth noting in your docs, or include it as part of your own styles.

**Comment by rebz** [comment]
Thank you for making this. Super helpful and much appreciated!
