### ISSUE TITLE
Programmatically controlling the Video

### ISSUE THREAD

**Issue by 19peaches** [redxtech/vue-plyr#30]
Great package.

I'm a bit confused on how I can control the playback programatically. I'm showing the player in a modal and when it gets closed I need the playback to be paused, if it's reopened then to play.

I'm sure there's a simple way to do that, I'm just not seeing it in your documentation.

Thanks.

**Comment by 1e4** [comment]
You can refer to [this ticket](https://github.com/redxtech/vue-plyr/issues/12#issuecomment-420373831), has all you need.

**Comment by 19peaches** [comment]
No worries, I decide to use the Plyr package directly in my component.

Thanks
