### ISSUE TITLE
Build css fail with Nuxtjs

### ISSUE THREAD

**Issue by standfv** [redxtech/vue-plyr#35]
error  in ./node_modules/plyr/dist/plyr.css
Module build failed (from ./node_modules/css-loader/index.js):
Unclosed bracket (1:9591)

@ ./node_modules/plyr/dist/plyr.css 4:14-133 14:3-18:5 15:22-141
 @ ./node_modules/vue-plyr/dist/vue-plyr.es.js
 @ ./plugins/vue-plyr.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

**Comment by redxtech** [comment]
Closing in favour of #32
