### ISSUE TITLE
Hooking into events on button presses

### ISSUE THREAD

**Issue by 1e4** [redxtech/vue-plyr#36]
Hi there,

I'm looking to hook into certain buttons and changes rather than the events themselves. The problem with hooking into the play event or the state change for example, is that as far as I can see you can't tell if the play/pause button was pressed. Same goes for volume and seeking.

Is there anyway to differentiate between a button click or an event?

Thanks for the package - it's been a huge help.

**Comment by 1e4** [comment]
Reopening as I've reworded how to ask and read the documentation a little more.

**Comment by redxtech** [comment]
Hey - I would recommend reading the docs over at sampotts/plyr to get this accomplished. If you can't find it anywhere in there, feel free to open an issue on that github repo. He's the creator of the lib - I just made a wrapper.

**Comment by 1e4** [comment]
Hi @redxtech I've looked into it a little more, passing controls can be done via a function, is there anyway to use vue events within the template? For instance I want to bind something to `@click` but if I just pass in the raw template it doesn't get compiled - I tried returning a component but that too seemed to not work. Any ideas?

**Comment by redxtech** [comment]
@1e4 can you show me a code example of where you do this?

**Comment by redxtech** [comment]
Unless stated in the plyr docs, you cannot hook onto button presses directly. Unless you have any further additions I will be closing this.
