### ISSUE TITLE
Syntax error when using with Nuxt

### ISSUE THREAD

**Issue by akarelas** [redxtech/vue-plyr#39]
I created a fresh nuxt app (with `npx create-nuxt-app my-plyr`), and did `npm i vye-plyr plyr`, and added the created `~/plugins/vue-plyr.js` with the two lines you mention:

```javascript
import 'vue-plyr'
import 'vue-plyr/dist/vue-plyr.css'
```

and included `'~/plugins/vue-plyr.js'` in `nuxt.config.js`'s plugins array.

I.e. I did everything as I should.

But `npm run dev` fails with an error:

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                  4:16:54 AM

 error  in ./node_modules/plyr/dist/plyr.css

Module build failed (from ./node_modules/css-loader/index.js):
Unclosed bracket (1:9688)
```

**Comment by redxtech** [comment]
Closing in favour of #32 & sampotts/plyr#1220
