### ISSUE TITLE
"Unknown custom element" when running with nuxt

### ISSUE THREAD

**Issue by akarelas** [redxtech/vue-plyr#40]
I followed the instructions for nuxt precisely, and don't get the player on the browser window.

Also, in the browser console I see the following error message:

![nuxt-error](https://user-images.githubusercontent.com/423822/47687810-d65c3f00-dbea-11e8-831c-00786c95c723.png)

**Comment by redxtech** [comment]
Closing in favour of #38 .
I'll work on this later today hopefully.
