### ISSUE TITLE
CJS incompatible

### ISSUE THREAD

**Issue by iCrawl** [redxtech/vue-plyr#43]
Can we remove this line here:
https://github.com/redxtech/vue-plyr/blob/master/src/VuePlyr.vue#L9
```js
import 'plyr/dist/plyr.css'
```

I feel its unnecessary in there and you could just mention, like in previous versions to to import:
`import 'vue-plyr/dist/plyr.css'`

The reason it breaks is simple if you look into the dist/ folder `vue-plyr.cjs.js`, the import transpiles down to `require('plyr/dist/plyr.css')` which throws a nice error since a css file is sadly not something require can handle.

**Comment by akarelas** [comment]
I agree with @iCrawl . The title of her issue could also be called 'nuxt incompatible'.

Without her fix, `vue-plyr` doesn't work on nuxt. With her fix it does.

Could you take it into consideration?

**Comment by redxtech** [comment]
I'm working on this one right now. Sorry for the wait.

**Comment by redxtech** [comment]
I'm working on fixing this one right now. It's taking a little bit of time to work out all types of compatibility but once I get vue-cli & nuxt worked out I will push a new version with this fix.

**Comment by redxtech** [comment]
I have pushed a fix to npm (v5.1.0) that should fix this issue. Sorry for the long wait I just had a bunch of personal stuff going on. @iCrawl test it out and let me know the results.

**Comment by rhwilr** [comment]
@redxtech Thanks for fixing the issue.
I tried to test it out, but the latest release on npm is [5.0.4. ](https://www.npmjs.com/package/vue-plyr?activeTab=versions)

**Comment by redxtech** [comment]
Whoops forgot to publish it. @rhwilr should be updated now. Try again.

**Comment by rhwilr** [comment]
:+1: Perfect! now it works 
And at least for me the issue seems to be fixed :tada:
Thanks for the great work!

**Comment by redxtech** [comment]
Sounds good. I'll close this issue in a day or two if no one has any problems. If you do have problems let me know and I'll try to fix them and won't close it until those are finished.

**Comment by redxtech** [comment]
Ok since there have been no problems yet I will close this issue. Let me know if anything pops up.
