### ISSUE TITLE
Vue plyr component not being rendered on refresh

### ISSUE THREAD

**Issue by Kurtmcmurt** [redxtech/vue-plyr#443]
Hi all, 

We have a dynamic page in our nuxt build (_page_slug.vue) which is built by components defined in a call. There is a component which is called `slices.vue` and this a dynamic component. 

One of the components contains the `vue plyr` component. The data called in to populate the page is handled with `asyncData` and everything works when navigating with Nuxt/router links. *But* when refreshing, every other "slice" is rendered except `vue-plyr`. 

When checking the inspector, it's showing the component tags and props i.e. it hasn't rendered. We're pulling it in in the standard way - via a plugin and the implementation mirrors that of the docs. I'm just hoping maybe someone might just go "ahhh it's because of this", it's done my head right in. 

This isn't happening in development, only in production so I'm concerned there's a Webpack/compilation issue somewhere...

Any help would be greatly appreciated. Sorry if this isn't in a preferred format, I'm on my phone.

**Comment by collinped** [comment]
Try wrapping it in ```<client-only>``` like so:

```
<client-only>
  <vue-plyr>
    <div data-plyr-provider="youtube" data-plyr-embed-id="bTqVqk7FSmY"></div>
  </vue-plyr>
</client-only>
```

**Comment by Kurtmcmurt** [comment]
@collinped haha I saw that in the docs but assumed since the plugin was being brought in as client-only, I wouldn't need that... Wrong! Thanks for you help man 💯🤘

**Comment by vin-ni** [comment]
I get the same error on the official nuxt demo. The videos are not loading:

![Screenshot 2021-09-22 at 12 31 15](https://user-images.githubusercontent.com/9806572/134328320-bdcf8600-2307-4467-be31-91e037402d8f.png)
![Screenshot 2021-09-22 at 12 31 23](https://user-images.githubusercontent.com/9806572/134328337-695f3fdb-ed66-448e-a330-4b65b3a7735d.png)
