### ISSUE TITLE
autoplay options not working

### ISSUE THREAD

**Issue by yonghing** [redxtech/vue-plyr#48]
autoplay options give 'Uncaught (in promise) DOMException' error

<vue-plyr :options="{ autoplay: true}">

**Comment by yonghing** [comment]
<video autoplay muted> </video> 
this is working fine

Can you give example, how to use :options ?

**Comment by redxtech** [comment]
Here's some example code for how to use options:
```vue
<template>
  <vue-plyr
    ref="player"
    :options="options"
  ></vue-plyr>
</template>
<script>
  name: 'Component',
  data () {
    return {
      options: {} // put your options in the object here.
    }
  },
  mounted () {
    this.player.on('event', () => console.log('event fired'))
  },
  computed: {
    player () { return this.$refs.player.player }
  }
</script>
```

I find that using YouTube give a bunch of DOMException errors that are unrelated to anything I'm able to do with it. Unless they're actually inhibiting your site from working I would recommend ignoring them. If they happen to be breaking your site open an issue with sampotts/plyr as he's the maintainer of the plyr library used in this plugin.

**Comment by redxtech** [comment]
I feel that this is most likely a problem with the upstream [plyr](/sampotts/plyr) if it is a problem. I'll close the issue here and you can open one up there. If it is indeed an issue with this one, I can take a look into it but you will need to give a few more details.
