### ISSUE TITLE
Documentation leaves readers thinking vue-plyr works with nuxt

### ISSUE THREAD

**Issue by akarelas** [redxtech/vue-plyr#49]
This section needs to be changed: https://github.com/redxtech/vue-plyr#ssr
The way it is now, causes people (users of nuxt) to think that there is something wrong with them, and they will try for hours to figure out what it is they're doing wrong in the hope of getting vue-plyr working with their site. I think that's not very respectful of other human beings and their time.

Another option is to resolve this issue is by fixing bug #43 (which has been there for two months).

**Comment by redxtech** [comment]
I have updated both the package and the documentation so that this is no longer relevant. You now need to include the css manually in both means of installation and I have updated the docs to reflect so.
