### ISSUE TITLE
NPM Package is empty

### ISSUE THREAD

**Issue by superbiche** [redxtech/vue-plyr#57]
Hi,

Seems the last version is empty : https://d.pr/i/kHH58x

And: https://d.pr/i/sHYnzN

If I use 5.1.0: https://d.pr/i/dqfulS

Please fix the NPM package for 5.1.2 😺.

**Comment by bitbirddev** [comment]
same problem here

**Comment by afv** [comment]
You can also check it here:
https://unpkg.com/vue-plyr@5.1.1/ - has "dist"
https://unpkg.com/vue-plyr@5.1.2/ - has no "dist"

**Comment by redxtech** [comment]
Pushing update to fix this now.

**Comment by redxtech** [comment]
Latest update should have fixed this. Let me know if it continues.
