### ISSUE TITLE
source setter

### ISSUE THREAD

**Issue by Carmichaeldb** [redxtech/vue-plyr#59]
How do I use the .source setter on the vue-plyr? the regular js plyr example for youtube is:
player.source = {
    type: 'video',
    sources: [
        {
            src: 'bTqVqk7FSmY',
            provider: 'youtube',
        },
    ],
};

**Comment by Carmichaeldb** [comment]
I wasn't able to figure this out so I am just feeding the player the url with the video id via a computed property, but I can't seem to get it to change the video id of the next video when the player is finished. Anyone able to help?

**Comment by hoangdangduy** [comment]
I also have a question.
Seem vue-plyr don't support setter source.

**Comment by ryanhuellen** [comment]
Would also like to see this, same issue.

**Comment by redxtech** [comment]
Once you access the plyr instance, you should be able to use the `source` setter/getter as described here: https://github.com/sampotts/plyr#the-source-setter
