### ISSUE TITLE
[Plyr Interface] Provide a way to change the Interface language

### ISSUE THREAD

**Issue by Vahagn-Zaqaryan** [redxtech/vue-plyr#68]
### What is the Problem?
In my project, there is a need to change the plyr interface language when the user is not understanding the default language of the interface.

**Comment by redxtech** [comment]
You should be able to use the player instance and change the language using the `language` property described [here](https://github.com/sampotts/plyr#getters-and-setters).

If that doesn't work feel free to re-open this issue.
