### ISSUE TITLE
In the case of multiple instances, can't get an instance?

### ISSUE THREAD

**Issue by sai2333** [redxtech/vue-plyr#79]
![image](https://user-images.githubusercontent.com/27514272/61045813-30660300-a40e-11e9-9c17-4199f5c04b9c.png)
```javascript
computed: {
    player() {
      return this.$refs.plyr[0].player;
    }
  },
```
![image](https://user-images.githubusercontent.com/27514272/61045863-4d9ad180-a40e-11e9-8b9f-74853a562811.png)
If there is only one instance, the situation is normal.
Thank you for taking the time to answer my questions.

**Comment by redxtech** [comment]
Use a different ref for each instance.
