### ISSUE TITLE
SSR compability

### ISSUE THREAD

**Issue by iCrawl** [redxtech/vue-plyr#8]
Is there any plan on doing this?

I saw in #7 that you plan on upgrading to plyr version 3, so could you take a look at that?
It's basically just checking if `window` exists before doing any operations that only the client should do.

Something like `if (typeof window !== 'undefined')` should usually do the trick.
If that isn't desired, I can maintain my own fork.

Cheers.

**Comment by redxtech** [comment]
Sounds good. I can do that as well. Also, isn't the mounted() method not called on the server ? Wouldn't putting in there be fine? I don't have any experience with SSR so not 100% sure what goes where. I can also do this tonight as well.

**Comment by iCrawl** [comment]
Ah, if thats the only place you use it that should be fine yea.

But I guess my issue is pointing at plyr itself as it seems. You import it in the script tag (like you kinda have to) and plyr then already tries to associate with document as it seems.

![image](https://user-images.githubusercontent.com/20760160/37692911-2a3071f2-2cbc-11e8-8f61-0b1faaaab2cf.png)

The relevant portion of that code is here:
![image](https://user-images.githubusercontent.com/20760160/37692923-41e02e78-2cbc-11e8-8cbb-6f1c8fa601ba.png)

I'm a bit unsure if this is an easy fix at the moment. I'm not sure about the implications of importing only on the client 🤔

**Comment by redxtech** [comment]
Ah ok. I'll see if I can do a conditional import within the mounted hook to fix that.
Can you push that to a github repo (or a branch if it's an existing project) so I can clone it and run to see if I got it working ?

**Comment by iCrawl** [comment]
This project is sadly not open to the public, but you can simply use this example here with ream:
https://github.com/ream/ream/tree/master/examples/custom-root-component
And just import vue-plyr into the index.js and you'll immediately see the error, you don't even need to include it in the Root component for the error to pop up.

**Comment by redxtech** [comment]
Sounds good. I'll take a look at this as soon as I've added v3 support.

**Comment by iCrawl** [comment]
After some testing, an easy way around it would be:

```vue
<template>
      <div>
            <plyr>
                  <audio><source :src="somelink"></audio>
            </plyr>
      </div>
</template>

<script>
if (process.browser) var { Plyr } = require('vue-plyr');

export default {
	components: {
		plyr: Plyr
	},
        ...
</script>
```

One would have to do that for every component that plyr is needed, since the usual import into `index.js` and then apply `Vue.use()` wont work.

**Comment by redxtech** [comment]
That does seem to work. Give me a sec and I'll throw that into the component by default.

**Comment by iCrawl** [comment]
I assume you want me to do it the usual way right?

```js
import VuePlyr from '../../vue-plyr/dist/vue-plyr';
Vue.use(VuePlyr);
```

If so, no that did not do the trick.

**Comment by redxtech** [comment]
@iCrawl Hmm. I'll give that look

**Comment by redxtech** [comment]
@iCrawl ok so I did that and it's working just fine. Here's what I have:
I extended the ream example root component. Only file that I changed was the index file:
```js
// index.js
import Vue from 'vue'
import Router from 'vue-router'
import VuePlyr from '../../../vue-plyr/src/index.js'

Vue.use(Router)
Vue.use(VuePlyr)

export default {
  root: () => import('./Root.vue'),
  router: () => new Router({
    mode: 'history',
    routes: [
      {
        path: '/',
        component: {
          render(h) {
            return h('h1', 'homepage')
          }
        }
      },
      {
        path: '/plyr',
        component: {
          render (h) {
            return h('plyr-video', {
              props: {
                poster: 'https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.jpg?v1',
                videos: [{ src: 'https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.mp4', format: 'mp4' }],
                subtitles: [{ src: 'https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.en.vtt', label: 'English', srclang: 'en' }],
                crossorigin: true
              }
            })
          }
        }
      }
    ]
  })
}
```

**Comment by iCrawl** [comment]
Oh jeez, I was importing the wrong thing as it seems. Now that's embarrassing, haha 😃 

Thank you very much, I would say this is resolved then!

**Comment by redxtech** [comment]
Sounds good. I will push a release to npm (v3 for plyr v3) later today.
Happy to help \:)
