### ISSUE TITLE
how could I update the poster in video

### ISSUE THREAD

**Issue by wakaryry** [redxtech/vue-plyr#82]
I got a table of video list.

But when I delete a video, and remove it from the table list, other videos' poster is not correct.

How could I make the poster correct with no refresh of the page?

Thanks.

![image](https://user-images.githubusercontent.com/7576559/61855449-aaa88400-aef2-11e9-80b0-75cba9556998.png)

**Comment by redxtech** [comment]
Using the `key` attribute on each element should do the trick. Set `key` to the poster link, that way if it is changed the image will change as well.

**Comment by redxtech** [comment]
I'm going to close this since there haven't been any updates in a while.
