### ISSUE TITLE
Audio only plays once on iOS Safari & Chrome Mobile

### ISSUE THREAD

**Issue by daverydan** [redxtech/vue-plyr#83]
Audio will only play once on iOS Safari & Chrome mobile. When clicking play on vue-plyr it plays the first time and then will not play again. What's weird is if I lock my iPhone then unlock it and hit play, it will play every time. Any ideas? I have confirmed that it works on Android. Thanks!

**Comment by redxtech** [comment]
Honestly I have no clue. Take it up with [upstream](/sampotts/plyr).
