### ISSUE TITLE
Problems with controls

### ISSUE THREAD

**Issue by lewdias** [redxtech/vue-plyr#84]
Hello!

In the Plyr github page, it shows that most controls are active by default, but when using this plugin for Vue, the only thing i get is Speed (for YouTube) and Speed + Captions (for Vimeo).

Also, the tracker seems really small for no reason.
I tried downgrading to 5.1.0 and it didnt help for both issues.

![Captura de Tela 2019-08-06 às 11 23 40](https://user-images.githubusercontent.com/26660980/62548175-c1c56b00-b83c-11e9-8674-056898726a16.png)

YouTube iframe:
I can change some options (like loop and change the speed values) but i cant seem to make buttons show up.
Also, the quality array/object is empty:
![Captura de Tela 2019-08-06 às 11 55 32](https://user-images.githubusercontent.com/26660980/62550831-4b773780-b841-11e9-95e6-65f582d956a9.png)

Edit: Adding that i get the option to change speed in vimeo aswell.
Edit2: New information about the options.

**Comment by francoism90** [comment]
Having the same issue, using the plyr sass instead of the provided css fixed the issue:
`@import '~plyr/src/sass/plyr';`

Seems the latest changes hasn't been pushed to NPM, don't know if these issues has been fixed.

**Comment by lewdias** [comment]
Hello Francoism90,

That fixed the bar, but the issues with the controls are still present.

Also, im using less, so i used the css file from the dist folder.

Thank you!

**Comment by francoism90** [comment]
@lewdias It seems a bit weird the CSS needs to imported twice as it seem to happen already with the component itself. But maybe I'm mistaken, hope it can be fixed. :)

**Comment by securedeveloper** [comment]
This is my way of passing custom controls and it seems to be working
```js
<template>
    <vue-plyr
        ref="plyr"
        :options="playerOptions">
        <div
            data-plyr-provider="youtube"
            :data-plyr-embed-id="src"/>
    </vue-plyr>
</template>
<script>
    export default {
        data () {
            return {
                playerOptions: {
                    controls: [
                        'play-large',
                        'mute',
                        'fullscreen'
                    ]
                }
            }
        },
        props: {
            src: String
        },
        computed: {
            player () {
                return this.$refs.plyr.player
            }
        }
    }
</script>
```

**Comment by redxtech** [comment]
That is how you should be doing it.
The CSS should now come bundled.
I'll close this now, feel free to re-open if there's anything else.

**Comment by mortensassi** [comment]
For me it is still not working to override the SASS Variables since there is already the built CSS included. I am now currently unable to just set another color after importing the plyr SCSS, which needs me to move to the above mentioned alternative. Hope you'll fix this any soon
